### ISSUE TITLE
[Boilerplate] Frontend Boilerplate

### ISSUE THREAD

**Issue by sooojungee** [woowa-techcamp-2020/hkb-4#3]
- [x] index.html 설정
- [x] index.js 설정
- [x] 디렉토리 구조 설정

**Comment by eunjung-jenny** [comment]
프론트는 테스트 폴더 없어도 되나요?

**Comment by sooojungee** [comment]
오 갑자기 메일로 왔어요!
사실 저도 잘 모르게써염..
프론트에서도 할까요?
추가해볼게요..!
