### ISSUE TITLE
[레이아웃] 레이아웃 페이지 개발

### ISSUE THREAD

**Issue by sooojungee** [woowa-techcamp-2020/hkb-4#8]
- [x] header 마크업
- [x] 로그인 후, header에 사용자 이름 보여주기
- [x] 번들링된 파일과 연결

**Comment by eunjung-jenny** [comment]
번들링된 파일과 연결 이 무슨 뜻인가요? ㅠ.ㅠ

**Comment by sooojungee** [comment]
오세상에나 제가 사실 말을 잘 못합니당 ㅜㅜ
그뭐지 webpack에서 만든 bundle.js랑 연결하기..?
이런거에염 ㅜㅜ
